services:
  webapi:
    container_name: webapi_container
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql_container;Port=3306;Database=SampleDB;User=sara;Password=mysecretpassword
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - dev_network
  mysql_db:
    container_name: mysql_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: SampleDB
      MYSQL_USER: sara
      MYSQL_PASSWORD: mysecretpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - dev_network
    restart: unless-stopped

  adminer:
    container_name: adminer_container
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - dev_network
    restart: unless-stopped

networks:
  dev_network:
    driver: bridge

volumes:
  mysql_data:
